#ifndef PREAMBLE_GLSL
#define PREAMBLE_GLSL

// Scene
#define SCENE_POSITION_ATTRIB_LOCATION 0
#define SCENE_TEXCOORD_ATTRIB_LOCATION 1
#define SCENE_NORMAL_ATTRIB_LOCATION 2

#define SCENE_DIFFUSE_MAP_TEXTURE_BINDING 0
#define SCENE_SHADOW_MAP_TEXTURE_BINDING 1
#define DEPTHVIS_DEPTH_MAP_TEXTURE_BINDING 0

#endif // PREAMBLE_GLSL
